name: setup-pnpm
description: 'Setup Node enviroment using pnpm'
inputs:
  node-version:
    description: 'Version for The Node'
    required: false
    default: '20'
  fetch-depth:
    description: 'Fetch depth for checkout'
    required: false
    default: '1'
  cache:
    description: 'Used to specify a package manager for caching in the default directory.'
    required: false
    default: ''
  registry-url:
    description: 'Optional registry to set up for auth.'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: Install pnpm
      uses: pnpm/action-setup@v4.1.0

    - name: Setup node (${{ inputs.node-version }})
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.cache }}
        registry-url: ${{ inputs.registry-url }}

    - name: Install dependencies
      shell: bash
      run: pnpm install
